---
version: '3'
services:
  frontend:
    image: shuddd/frontend
    ports: 
      - 4200:3000
    depends_on: 
      - backend
    networks: 
      - server
  backend: 
    image: shuddd/backend
    ports: 
      - 8085:8085
    depends_on: 
      - db
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tripbuddy
      SPRING_DATASOURCE_USERNAME: shuddd
      SPRING_DATASOURCE_PASSWORD: password
    networks: 
      - server
      - database
  db: 
    image: mysql:8.0
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: tripbuddy
      MYSQL_USER: shuddd
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - database
    volumes: 
      - dbstore:/var/lib/mysql
networks: 
  server: 
  database: 
volumes: 
  dbstore:
